version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: gis-converter-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /tmp/gis_uploads:/tmp/gis_uploads
      - /tmp/gis_outputs:/tmp/gis_outputs
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: gis-converter-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  gis_uploads:
  gis_outputs:
